import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from '@/components/Sidebar';
import "@/app/globals.css";
import styles from './layout.module.css'; // Import the module CSS

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={styles.maincontainer}>
      {/* <header>
        <h1>Tweeter</h1>
      </header> */}
      <div className="col-md-3">
        <Sidebar />
      </div>
      <main className="col-md-9 p-6 w-full">
      {/* <main className={`${styles.tweetlistcontainer} col-md-9 p-6 w-full`}> */}
        {children}
      </main>
      {/* <footer>
        <p>&copy; 2024 My App</p>
      </footer> */}
    </div>
  );
}
